name: Publish NPM package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - name: Build plugin
        run: npm run build
      - name: Publish plugin
        run: npm publish --access public --tag ${{ github.event.release.prerelease && 'preview' || 'latest' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      - name: publish-with-yarn
        uses: simenandre/publish-with-yarn@v2.0.0
        env:
          npm_auth_token: ${{ secrets.NPM_PUBLISH_TOKEN }}
